spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://postgres:5432/tasksdb}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    changeLogFile: db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
